import type { SettlementMeta, SettlementSlug } from "./types.js";

export const settlements = Object.freeze([
  {
    slug: "abinsk",
    code: "ABINSK",
    nameRu: "Абинск",
    nameEn: "Abinsk",
    aliases: [],
  },
  {
    slug: "anapa",
    code: "ANAPA",
    nameRu: "Анапа",
    nameEn: "Anapa",
    aliases: [],
  },
  {
    slug: "apsheronsk",
    code: "APSHERONSK",
    nameRu: "Апшеронск",
    nameEn: "Apsheronsk",
    aliases: ["Absheronsk"],
  },
  {
    slug: "armavir",
    code: "ARMAVIR",
    nameRu: "Армавир",
    nameEn: "Armavir",
    aliases: [],
  },
  {
    slug: "belorechensk",
    code: "BELORECHENSK",
    nameRu: "Белореченск",
    nameEn: "Belorechensk",
    aliases: [],
  },
  {
    slug: "gelendzhik",
    code: "GELENDZHIK",
    nameRu: "Геленджик",
    nameEn: "Gelendzhik",
    aliases: ["Gelendjik"],
  },
  {
    slug: "goryachy-klyuch",
    code: "GORYACHY_KLYUCH",
    nameRu: "Горячий Ключ",
    nameEn: "Goryachy Klyuch",
    aliases: ["Goryachiy Klyuch"],
  },
  {
    slug: "gulkevichi",
    code: "GULKEVICHI",
    nameRu: "Гулькевичи",
    nameEn: "Gulkevichi",
    aliases: [],
  },
  {
    slug: "yeysk",
    code: "YEYSK",
    nameRu: "Ейск",
    nameEn: "Yeysk",
    aliases: ["Yeisk", "Eysk"],
  },
  {
    slug: "korenovsk",
    code: "KORENOVSK",
    nameRu: "Кореновск",
    nameEn: "Korenovsk",
    aliases: [],
  },
  {
    slug: "krasnodar",
    code: "KRASNODAR",
    nameRu: "Краснодар",
    nameEn: "Krasnodar",
    aliases: ["Екатеринодар", "Yekaterinodar", "Ekaterinodar"],
  },
  {
    slug: "kropotkin",
    code: "KROPOTKIN",
    nameRu: "Кропоткин",
    nameEn: "Kropotkin",
    aliases: [],
  },
  {
    slug: "krymsk",
    code: "KRYMSK",
    nameRu: "Крымск",
    nameEn: "Krymsk",
    aliases: [],
  },
  {
    slug: "kurganinsk",
    code: "KURGANINSK",
    nameRu: "Курганинск",
    nameEn: "Kurganinsk",
    aliases: [],
  },
  {
    slug: "labinsk",
    code: "LABINSK",
    nameRu: "Лабинск",
    nameEn: "Labinsk",
    aliases: [],
  },
  {
    slug: "novokubansk",
    code: "NOVOKUBANSK",
    nameRu: "Новокубанск",
    nameEn: "Novokubansk",
    aliases: [],
  },
  {
    slug: "novorossiysk",
    code: "NOVOROSSIYSK",
    nameRu: "Новороссийск",
    nameEn: "Novorossiysk",
    aliases: ["Novorossiisk", "Novorossisk"],
  },
  {
    slug: "primorsko-akhtarsk",
    code: "PRIMORSKO_AKHTARSK",
    nameRu: "Приморско-Ахтарск",
    nameEn: "Primorsko-Akhtarsk",
    aliases: [],
  },
  {
    slug: "slavyansk-na-kubani",
    code: "SLAVYANSK_NA_KUBANI",
    nameRu: "Славянск-на-Кубани",
    nameEn: "Slavyansk-na-Kubani",
    aliases: ["Slavyansk-on-Kuban", "Slavyansk on Kuban", "Slaviansk-na-Kubani"],
  },
  {
    slug: "sochi",
    code: "SOCHI",
    nameRu: "Сочи",
    nameEn: "Sochi",
    aliases: [],
  },
  {
    slug: "temryuk",
    code: "TEMRYUK",
    nameRu: "Темрюк",
    nameEn: "Temryuk",
    aliases: ["Temriuk"],
  },
  {
    slug: "timashevsk",
    code: "TIMASHEVSK",
    nameRu: "Тимашёвск",
    nameEn: "Timashevsk",
    aliases: ["Timashyovsk"],
  },
  {
    slug: "tikhoretsk",
    code: "TIKHORETSK",
    nameRu: "Тихорецк",
    nameEn: "Tikhoretsk",
    aliases: [],
  },
  {
    slug: "tuapse",
    code: "TUAPSE",
    nameRu: "Туапсе",
    nameEn: "Tuapse",
    aliases: [],
  },
  {
    slug: "ust-labinsk",
    code: "UST_LABINSK",
    nameRu: "Усть-Лабинск",
    nameEn: "Ust-Labinsk",
    aliases: ["Ust Labinsk"],
  },
  {
    slug: "khadyzhensk",
    code: "KHADYZHENSK",
    nameRu: "Хадыженск",
    nameEn: "Khadyzhensk",
    aliases: ["Hadyzhensk"],
  },
]) as readonly SettlementMeta[];

export const settlementSlugs = Object.freeze(settlements.map((settlement) => settlement.slug)) as readonly SettlementSlug[];
